export const dummyNotificationTypes = [
  {
    id: 1,
    type: 'ed-1',
    title_id: 'Kedaluwarsa dalam 1 hari',
    title_en: 'Expired in 1 day',
  },
  {
    id: 2,
    type: 'ed-3',
    title_id: 'Kedaluwarsa dalam 3 hari',
    title_en: 'Expired in 3 days',
  },
  {
    id: 3,
    type: 'ed-10',
    title_id: 'Kedaluwarsa dalam 10 hari',
    title_en: 'Expired in 10 days',
  },
  {
    id: 4,
    type: 'ed-14',
    title_id: 'Kedaluwarsa dalam 14 hari',
    title_en: 'Expired in 14 days',
  },
  {
    id: 5,
    type: 'ed-30',
    title_id: 'Kedaluwarsa dalam 30 hari',
    title_en: 'Expired in 30 days',
  },
  {
    id: 6,
    type: 'order-create',
    title_id: 'Pesanan Dibuat',
    title_en: 'Order Created',
  },
  {
    id: 7,
    type: 'order-confirm',
    title_id: 'Pesanan Dikonfirmasi',
    title_en: 'Order Confirmed',
  },
  {
    id: 8,
    type: 'order-ship',
    title_id: 'Pesanan Dikirim',
    title_en: 'Order Shipped',
  },
  {
    id: 9,
    type: 'cap-80',
    title_id: 'Kapasitas lebih dari 80%',
    title_en: 'Capacity more than 80%',
  },
  {
    id: 10,
    type: 'over-stock',
    title_id: 'Stok melebihi batas maksimum',
    title_en: 'Stock greater than max',
  },
  {
    id: 11,
    type: 'less-stock',
    title_id: 'Stok kurang dari batas minimum',
    title_en: 'Stock lesser than min',
  },
  {
    id: 12,
    type: 'zero-stock',
    title_id: 'Stok Kosong',
    title_en: 'Material out of stock',
  },
  {
    id: 13,
    type: 'asset-max',
    title_id: 'Ekskursi Suhu melebihi batas maksimum',
    title_en: 'Excursion Temp Max',
  },
  {
    id: 14,
    type: 'asset-min',
    title_id: 'Ekskursi Suhu dibawah batas minimum',
    title_en: 'Excursion Temp Min',
  },
  {
    id: 15,
    type: 'monthly-report',
    title_id: 'Laporan Bulanan',
    title_en: 'Monthly Report',
  },
  {
    id: 16,
    type: 'yearly-report',
    title_id: 'Laporan Tahunan',
    title_en: 'Yearly Report',
  },
  {
    id: 17,
    type: 'vaccine-2',
    title_id: 'Pengingat Penyuntikan ke-2 (IM)',
    title_en: 'Reminder PEP Day 7 (IM)',
  },
  {
    id: 18,
    type: 'vaccine-3',
    title_id: 'Pengingat Penyuntikan ke-3 (IM)',
    title_en: 'Reminder PEP Day 21/28',
  },
  {
    id: 19,
    type: 'vaccine-7',
    title_id: 'Pengingat Penyuntikan Pra-Pajanan ke-2',
    title_en: 'Reminder Pre Exposure 2',
  },
  {
    id: 20,
    type: 'book-all-entity',
    title_id: 'Buku Stok',
    title_en: 'Book Stock',
  },
  {
    id: 21,
    type: 'vaccine-8',
    title_id: 'Pengingat Penyuntikan ke-2 (ID)',
    title_en: 'Reminder PEP Day 3',
  },
  {
    id: 22,
    type: 'vaccine-2-2',
    title_id: 'Pengingat Penyuntikan ke-3 (ID)',
    title_en: 'Reminder PEP Day 7 (ID)',
  },
  {
    id: 23,
    type: 'ed-60',
    title_id: 'Kedaluwarsa dalam 60 hari',
    title_en: 'Expired in 60 days',
  },
  {
    id: 24,
    type: 'ed-90',
    title_id: 'Kedaluwarsa dalam 90 hari',
    title_en: 'Expired in 90 days',
  },
  {
    id: 25,
    type: 'asset-maintenance',
    title_id: 'Pengingat jadwal maintenance',
    title_en: 'Reminder scheduled maintenance',
  },
  {
    id: 26,
    type: 'asset-calibration',
    title_id: 'Pengingat jadwal kalibrasi',
    title_en: 'Reminder scheduled calibration',
  },
]
